# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91dfe71b4a901f6759b32d614ebf5712aa00e891555e379cffba0dc597cd5dd0616d2b36e09915482b0408b0a6227c2dbbfb494577ee3b86a9e2b23b1cb3025e

test:
  secret_key_base: 069a285826ecb0cdd0dacb7b3bf5b88dd8397a5a17ffcfadcd596ec776317956622f43038b0e92c5d23ff9b30e0ccbe8af901c53416339d1577b2d2c7d184ca3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
